(setq web-html-complete-table (make-hash-table :test 'equal))
(puthash "a" (list "accesskey" "coords" "download" "href" "hreflang" "name" "rel" "rev" "shape" "tabindex" "target" "title" "type") web-html-complete-table)
(puthash "abbr" (list "title") web-html-complete-table)
(puthash "applet" (list "align" "alt" "archive" "code" "codebase" "height" "hspace" "vspace" "width") web-html-complete-table)
(puthash "area" (list "accesskey" "alt" "coords" "href" "hreflang" "nohref" "shape" "tabindex" "target" "type") web-html-complete-table)
(puthash "audio" (list "autoplay" "controls" "loop" "muted" "preload" "src") web-html-complete-table)
(puthash "base" (list "href" "target") web-html-complete-table)
(puthash "basefont" (list "color" "face" "size") web-html-complete-table)
(puthash "bdo" (list "dir") web-html-complete-table)
(puthash "bgsound" (list "balance" "loop" "src" "volume") web-html-complete-table)
(puthash "body" (list "alink" "background" "bgcolor" "bgproperties" "bottommargin" "leftmargin" "link" "rightmargin" "scroll" "text" "topmargin" "vlink") web-html-complete-table)
(puthash "br" (list "clear") web-html-complete-table)
(puthash "button" (list "accesskey" "autofocus" "disabled" "form" "formaction" "formenctype" "formmethod" "formnovalidate" "formtarget" "name" "type" "value") web-html-complete-table)
(puthash "caption" (list "align" "valign") web-html-complete-table)
(puthash "col" (list "align" "char" "charoff" "span" "valign" "width") web-html-complete-table)
(puthash "colgroup" (list "align" "char" "charoff" "span" "valign" "width") web-html-complete-table)
(puthash "del" (list "cite" "datetime") web-html-complete-table)
(puthash "div" (list "align" "title") web-html-complete-table)
(puthash "embed" (list "align" "height" "hidden" "hspace" "pluginspage" "src" "type" "vspace" "width") web-html-complete-table)
(puthash "fieldset" (list "disabled" "form" "title") web-html-complete-table)
(puthash "font" (list "color" "face" "size") web-html-complete-table)
(puthash "form" (list "accept-charset" "action" "autocomplete" "enctype" "method" "name" "novalidate" "target") web-html-complete-table)
(puthash "frame" (list "bordercolor" "frameborder" "name" "noresize" "scrolling" "src") web-html-complete-table)
(puthash "frameset" (list "border" "bordercolor" "cols" "frameborder" "framespacing" "rows") web-html-complete-table)
(puthash "h1" (list "align") web-html-complete-table)
(puthash "h2" (list "align") web-html-complete-table)
(puthash "h3" (list "align") web-html-complete-table)
(puthash "h4" (list "align") web-html-complete-table)
(puthash "h5" (list "align") web-html-complete-table)
(puthash "h6" (list "align") web-html-complete-table)
(puthash "head" (list "profile") web-html-complete-table)
(puthash "hr" (list "align" "color" "noshade" "size" "width") web-html-complete-table)
(puthash "html" (list "manifest" "title" "xmlns") web-html-complete-table)
(puthash "iframe" (list "align" "allowtransparency" "frameborder" "height" "hspace" "marginheight" "marginwidth" "name" "sandbox" "scrolling" "seamless" "src" "srcdoc" "vspace" "width") web-html-complete-table)
(puthash "img" (list "align" "alt" "border" "height" "hspace" "ismap" "longdesc" "lowsrc" "src" "usemap" "vspace" "width") web-html-complete-table)
(puthash "input" (list "accept" "accesskey" "align" "alt" "autocomplete" "autofocus" "border" "checked" "disabled" "form" "formaction" "formenctype" "formmethod" "formnovalidate" "formtarget" "list" "max" "maxlength" "min" "multiple" "name" "pattern" "placeholder" "readonly" "required" "size" "src" "step" "tabindex" "type" "value") web-html-complete-table)
(puthash "ins" (list "cite" "datetime") web-html-complete-table)
(puthash "label" (list "accesskey" "for") web-html-complete-table)
(puthash "legend" (list "accesskey" "align" "title") web-html-complete-table)
(puthash "li" (list "type" "value") web-html-complete-table)
(puthash "link" (list "charset" "href" "media" "rel" "sizes" "type") web-html-complete-table)
(puthash "map" (list "name") web-html-complete-table)
(puthash "marquee" (list "behavior" "bgcolor" "direction" "height" "hspace" "loop" "scrollamount" "scrolldelay" "truespeed" "vspace" "width") web-html-complete-table)
(puthash "menu" (list "label" "type") web-html-complete-table)
(puthash "meta" (list "charset" "content" "http-equiv" "name") web-html-complete-table)
(puthash "meter" (list "high" "low" "max" "min" "optimum" "value") web-html-complete-table)
(puthash "object" (list "align" "archive" "classid" "code" "codebase" "codetype" "data" "height" "hspace" "tabindex" "type" "vspace" "width") web-html-complete-table)
(puthash "ol" (list "reversed" "start" "type") web-html-complete-table)
(puthash "optgroup" (list "disabled" "label") web-html-complete-table)
(puthash "option" (list "disabled" "label" "selected" "value") web-html-complete-table)
(puthash "p" (list "align") web-html-complete-table)
(puthash "param" (list "name" "type" "value" "valuetype") web-html-complete-table)
(puthash "script" (list "async" "defer" "language" "src" "type") web-html-complete-table)
(puthash "select" (list "accesskey" "autofocus" "disabled" "form" "multiple" "name" "required" "size" "tabindex") web-html-complete-table)
(puthash "source" (list "media" "src" "type") web-html-complete-table)
(puthash "style" (list "media" "type") web-html-complete-table)
(puthash "table" (list "align" "background" "bgcolor" "border" "bordercolor" "cellpadding" "cellspacing" "cols" "frame" "height" "rules" "summary" "width") web-html-complete-table)
(puthash "tbody" (list "align" "bgcolor" "char" "charoff" "valign") web-html-complete-table)
(puthash "td" (list "abbr" "align" "axis" "background" "bgcolor" "bordercolor" "char" "charoff" "colspan" "headers" "height" "nowrap" "rowspan" "scope" "valign" "width") web-html-complete-table)
(puthash "textarea" (list "accesskey" "autofocus" "cols" "disabled" "form" "maxlength" "name" "placeholder" "readonly" "required" "rows" "tabindex" "wrap") web-html-complete-table)
(puthash "tfoot" (list "align" "bgcolor" "char" "charoff" "valign") web-html-complete-table)
(puthash "th" (list "abbr" "align" "axis" "background" "bgcolor" "bordercolor" "char" "charoff" "colspan" "headers" "height" "nowrap" "rowspan" "scope" "valign" "width") web-html-complete-table)
(puthash "thead" (list "align" "bgcolor" "char" "charoff" "valign") web-html-complete-table)
(puthash "time" (list "datetime" "pubdate") web-html-complete-table)
(puthash "tr" (list "align" "bgcolor" "bordercolor" "char" "charoff" "valign") web-html-complete-table)
(puthash "ul" (list "type") web-html-complete-table)
(puthash "video" (list "autoplay" "controls" "height" "loop" "poster" "preload" "src" "width") web-html-complete-table)


(require 'company)
(require 'cl-lib)
(require 'abbrev)

(defun company-web-mode-insert (match)
  "Replace MATCH with the expanded abbrev."
  (insert "aaaaa"))

(defun company-web-mode-meta (arg)
  "Replace MATCH with the expanded abbrev."
  "xxx")


;;;###autoload
(defun company-web (command &optional arg &rest ignored)
  "`company-mode' completion back-end for web-mode."
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-web-mode
                                        'company-web-mode-insert))
    (prefix (company-grab-symbol))
    (candidates (nconc
                 (delete "" (all-completions arg global-abbrev-table))
                 (delete "" (all-completions arg local-abbrev-table))))
    (meta (company-web-mode-meta arg))
    (require-match t)))

(provide 'company-web-mode)

;; (if (web-mode-is-html-tag)
;;     ())
